version: 2
updates:
  - package-ecosystem: "maven"
    directories:
      - "/etc/*/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
